In [81]:
import numpy as np
import pandas as pd
import os

In [82]:
os.chdir('D:\Data Science\Data Visualization Coursera\Assignment')
data = pd.read_csv('D:\Data Science\Data Visualization Coursera\Assignment\Topic_Survey_Assignment.csv', index_col = 0)
data

,Very interested,Somewhat interested,Not interested
Big Data (Spark / Hadoop),1332,729,127
Data Analysis / Statistics,1688,444,60
Data Journalism,429,1081,610
Data Visualization,1340,734,102
Deep Learning,1263,770,136
Machine Learning,1629,477,74

In [83]:
import matplotlib.pyplot as plt

In [84]:
d_sort = data.sort_values(['Very interested'], ascending = False)
d_sort

,Very interested,Somewhat interested,Not interested
Data Analysis / Statistics,1688,444,60
Machine Learning,1629,477,74
Data Visualization,1340,734,102
Big Data (Spark / Hadoop),1332,729,127
Deep Learning,1263,770,136
Data Journalism,429,1081,610

In [85]:
#Calculating percentages
Total = 2233
d_sort['Very interested'] = ((d_sort.iloc[:6, 0]/Total) * 100).round(2)
d_sort['Somewhat interested'] = ((d_sort.iloc[:6, 1]/Total) * 100).round(2)
d_sort['Not interested'] = ((d_sort.iloc[:6, 2]/Total) * 100).round(2)
d_sort

,Very interested,Somewhat interested,Not interested
Data Analysis / Statistics,75.59,19.88,2.69
Machine Learning,72.95,21.36,3.31
Data Visualization,60.01,32.87,4.57
Big Data (Spark / Hadoop),59.65,32.65,5.69
Deep Learning,56.56,34.48,6.09
Data Journalism,19.21,48.41,27.32

In [104]:
# Plotting graph

figure = ax.bar(d_sort, figsize = (20,8), color = ['#5cb85c','#5bc0de','#d9534f'], height = 5)

ax.set_xlabel('Respondent\'s interest', fontsize = 14) 
ax.set_ylabel('Different data science topics', fontsize = 14) 
ax.set_title('Percentage of the respondent\'s interest in Data Science areas', fontsize = 16) 

"""def autolabel(fig):

    Attach a text label above each bar displaying its height
    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width()/2., 1.05*height,
                '%d' % int(height),
                ha='center', va='bottom') """

plt.show()

TypeError: only size-1 arrays can be converted to Python scalars